#### b)

In [19]:
# Import necessary libraries
import numpy as np

In [21]:
# Define A
A = np.zeros((5, 3))
for i in range(1, 6):
    for j in range(1, 4):
        A[i-1, j-1] = np.sqrt(i**2 + j**2)

print(A)

[[1.41421356 2.23606798 3.16227766]
 [2.23606798 2.82842712 3.60555128]
 [3.16227766 3.60555128 4.24264069]
 [4.12310563 4.47213595 5.        ]
 [5.09901951 5.38516481 5.83095189]]


In [23]:
# Calculate Singular Value Decomposition (SVD)
U, S, Vt = np.linalg.svd(A)

In [32]:
# Find the indices of the zero singular values
zero_singular_values = np.isclose(S, 0)
print(zero_singular_values)
null_space_basis = Vt.T[:, zero_singular_values]

[False False False]


In [33]:
# Display the null space vectors
print("Null space vectors:")
print(null_space_basis)

Null space vectors:
[]
