## Question 3

In [43]:
# Import necessary libraries
import numpy as np
from scipy.linalg import solve

#### part a)

In [44]:
# Define N(t)
def N(t):
  return 0.3 + 2*t - 1.2*(t**2) + 0.5*(t**3)

# Define N_obs(t)
def N_obs(t):
  epsilons = np.random.normal(0, 0.01, 4)
  N_observed = 0.3 * 2*(t + epsilons[1]) - 1.2 * ((t + epsilons[2])**2) + 0.5 * ((t + epsilons[3])**3)
  return epsilons, N_observed

In [45]:
# Define a function for generating set of observations
def O_n(n):
  observations = []
  for i in range(1, n+1):
    t = i / (n+1)
    epsilons, N_observed = N_obs(t)
    observations.append((t, N_observed, epsilons))
  return observations

In [46]:
# Generate set of observations (O_n) and as well as A_n and b_n

# For n = 5
temp_5 = O_n(5)
O_5 = []
A_5 = []
b_5 = []
for element in temp_5:
  A_5.append(element[2])
  b_5.append(element[1])
  O_5.append((element[0], element[1]))


for i in range(len(A_5)):
  for j in range(4):
    if (j == 0):
      A_5[i][j] = 1
    elif (j == 1):
      A_5[i][j] = A_5[i][j]
    elif (j == 2):
      A_5[i][j] = (A_5[i][j]) ** 2
    elif (j == 3):
      A_5[i][j] = (A_5[i][j]) ** 3

print("------------------- O_5 -------------------")
for observation in O_5:
  print(observation)

print("\n ------------------- A_5 -------------------")
for row in A_5:
  print(row)

print("\n ------------------- b_5 -------------------")
for entry in b_5:
  print(entry)

------------------- O_5 -------------------
(0.16666666666666666, 0.060547897729073916)
(0.3333333333333333, 0.08660931161354476)
(0.5, 0.07205368524607522)
(0.6666666666666666, -0.003772024666931023)
(0.8333333333333334, -0.022712566840152826)

 ------------------- A_5 -------------------
[ 1.00000000e+00 -4.25400172e-03  2.03022490e-04  3.19043606e-09]
[1.00000000e+00 4.47510940e-03 4.98495699e-06 3.14714699e-08]
[ 1.00000000e+00  2.19569341e-02  1.05350332e-06 -2.34500750e-06]
[ 1.00000000e+00  6.68333197e-03  6.56706250e-05 -3.14263606e-06]
[1.00000000e+00 1.21578854e-02 9.52436892e-07 1.47618790e-06]

 ------------------- b_5 -------------------
0.060547897729073916
0.08660931161354476
0.07205368524607522
-0.003772024666931023
-0.022712566840152826


In [47]:
# For n = 10
temp_10 = O_n(10)
O_10 = []
A_10 = []
b_10 = []
for element in temp_10:
  A_10.append(element[2])
  b_10.append(element[1])
  O_10.append((element[0], element[1]))


for i in range(len(A_10)):
  for j in range(4):
    if (j == 0):
      A_10[i][j] = 1
    elif (j == 1):
      A_10[i][j] = A_10[i][j]
    elif (j == 2):
      A_10[i][j] = (A_10[i][j]) ** 2
    elif (j == 3):
      A_10[i][j] = (A_10[i][j]) ** 3

print("------------------- O_10 -------------------")
for observation in O_10:
  print(observation)

print("\n ------------------- A_10 -------------------")
for row in A_10:
  print(row)

print("\n ------------------- b_10 -------------------")
for entry in b_10:
  print(entry)

------------------- O_10 -------------------
(0.09090909090909091, 0.03934650056328065)
(0.18181818181818182, 0.08232060353031381)
(0.2727272727272727, 0.07151574031082833)
(0.36363636363636365, 0.07236891297115512)
(0.45454545454545453, 0.09434907902978298)
(0.5454545454545454, 0.03454171096159969)
(0.6363636363636364, -0.0062557536954444964)
(0.7272727272727273, 0.004561001565872691)
(0.8181818181818182, -0.03147026983701895)
(0.9090909090909091, -0.09270346987120914)

 ------------------- A_10 -------------------
[ 1.00000000e+00 -3.26414631e-03  2.36762261e-04 -1.17283773e-07]
[1.00000000e+00 7.18971658e-03 1.58355444e-04 1.62644940e-07]
[ 1.00000000e+00 -1.01696257e-02  1.00955094e-04 -6.57801354e-09]
[ 1.00000000e+00 -1.58646486e-02  2.44846009e-08 -4.82044000e-07]
[ 1.00000000e+00  4.58728300e-03  4.41844573e-04 -5.92112276e-07]
[ 1.00000000e+00 -1.61963951e-02  3.57332766e-05  4.47933881e-09]
[ 1.00000000e+00 -3.13673304e-03  1.74662837e-04 -3.14672616e-06]
[ 1.00000000e+00  5.

In [48]:
# For n = 100
temp_100 = O_n(100)
O_100 = []
A_100 = []
b_100 = []
for element in temp_100:
  A_100.append(element[2])
  b_100.append(element[1])
  O_100.append((element[0], element[1]))


for i in range(len(A_100)):
  for j in range(4):
    if (j == 0):
      A_100[i][j] = 1
    elif (j == 1):
      A_100[i][j] = A_100[i][j]
    elif (j == 2):
      A_100[i][j] = (A_100[i][j]) ** 2
    elif (j == 3):
      A_100[i][j] = (A_100[i][j]) ** 3

print("------------------- O_100 -------------------")
for observation in O_100:
  print(observation)

print("\n ------------------- A_100 -------------------")
for row in A_100:
  print(row)

print("\n ------------------- b_100 -------------------")
for entry in b_100:
  print(entry)

------------------- O_100 -------------------
(0.009900990099009901, 0.009012530885407344)
(0.019801980198019802, 0.004059616449683209)
(0.0297029702970297, 0.0104338245193674)
(0.039603960396039604, 0.023942298040149627)
(0.04950495049504951, 0.03150658175641698)
(0.0594059405940594, 0.03161713343146486)
(0.06930693069306931, 0.03937484101228347)
(0.07920792079207921, 0.037703477505532136)
(0.0891089108910891, 0.047159789788292966)
(0.09900990099009901, 0.046322741328392716)
(0.10891089108910891, 0.05363184893141232)
(0.1188118811881188, 0.050799287243472845)
(0.12871287128712872, 0.04860913418291653)
(0.13861386138613863, 0.06390653442805379)
(0.1485148514851485, 0.06252725778729834)
(0.15841584158415842, 0.06520744847316698)
(0.16831683168316833, 0.06603555658189023)
(0.1782178217821782, 0.06425291116844117)
(0.18811881188118812, 0.0788063389578126)
(0.19801980198019803, 0.07467851540232036)
(0.2079207920792079, 0.07001497798494646)
(0.21782178217821782, 0.07376658640025453)
(0.2277

#### part b)

I will use Augmented System techniques which is explained in lecture notes part 9.

In [49]:
# For simplicity I will convert A_n's b_n's to numpy arrays

A_5 = np.array(A_5)
b_5 = np.array(b_5)

A_10 = np.array(A_10)
b_10 = np.array(b_10)

A_100 = np.array(A_100)
b_100 = np.array(b_100)

In [50]:
# Define a function for augmented system construction
def BuildAugmentedSystem(A, b):
  # Make A and b numpy array if they are not
  A = np.array(A)
  b = np.array(b)

  # Dimensions
  m = A.shape[0]
  n = A.shape[1]

  # Construct I, A_T and O
  I = np.identity(m) # Identitiy matrix of size m*m
  A_T = A.transpose() # Transpose of A
  O = np.zeros((n,n)) # Zero matrix

  IA = np.hstack((I,A))
  A_TO = np.hstack((A_T, O))

  augmented_left = np.vstack((IA, A_TO))
  augmented_right = np.append(b, np.zeros((n)))

  return augmented_left, augmented_right


In [51]:
# Estimation for c_k for n = 5 (A_n  * c_k = b_n)

# Construct augmented system for n = 5
augmented_left_5, augmented_right_5 = BuildAugmentedSystem(A_5, b_5)

# Solve augmented system for n = 5
r_x = solve(augmented_left_5, augmented_right_5)

# x = c_k_5
c_k_5 = r_x[-4:]

print(c_k_5)

[ 3.86586355e-02 -4.72470150e-01  2.31170327e+01 -3.12827512e+03]


In [52]:
# Estimation for c_k for n = 10 (A_n  * c_k = b_n)

# Construct augmented system for n = 10
augmented_left_10, augmented_right_10 = BuildAugmentedSystem(A_10, b_10)

# Solve augmented system for n = 10
r_x = solve(augmented_left_10, augmented_right_10)

# x = c_k_10
c_k_10 = r_x[-4:]

print(c_k_10)

[-3.26035778e-03 -2.27982970e+00  2.71352297e+02  1.76264551e+04]


In [53]:
# Estimation for c_k for n = 100 (A_n  * c_k = b_n)

# Construct augmented system for n = 100
augmented_left_100, augmented_right_100 = BuildAugmentedSystem(A_100, b_100)

# Solve augmented system for n = 100
r_x = solve(augmented_left_100, augmented_right_100)

# x = c_k_10
c_k_100 = r_x[-4:]

print(c_k_100)

[ 2.96959662e-02 -1.40074439e+00 -4.84253060e+01  1.32509598e+03]


In [54]:
# Calculate average errors over a single run (just for experiment)

c_k = np.array([0.3, 2, -1.2, 0.5])

print("Error for a single run for n = 5: " , np.linalg.norm(c_k - c_k_5))
print("Error for a single run for n = 5: " , np.linalg.norm(c_k - c_k_10))
print("Error for a single run for n = 5: " , np.linalg.norm(c_k - c_k_100))

Error for a single run for n = 5:  3128.8706048789595
Error for a single run for n = 5:  17628.06275169971
Error for a single run for n = 5:  1325.4419537546141


#### part c)

In [55]:
# In order have multiple run, I will define a function to repeat the process above
def experiment(n):
  temp = O_n(n)
  O = []
  A = []
  b = []
  for element in temp:
    A.append(element[2])
    b.append(element[1])
    O.append((element[0], element[1]))


  for i in range(len(A)):
    for j in range(4):
      if (j == 0):
        A[i][j] = 1
      elif (j == 1):
        A[i][j] = A[i][j]
      elif (j == 2):
        A[i][j] = (A[i][j]) ** 2
      elif (j == 3):
        A[i][j] = (A[i][j]) ** 3

  augmented_left, augmented_right = BuildAugmentedSystem(A, b)

  r_x = solve(augmented_left, augmented_right)

  c_k_n = r_x[-4:]

  return c_k_n

In [56]:
# Calculate Average Errors over 1000 runs

avg_error_5 = 0
for i in range(1000):
  avg_error_5 += np.linalg.norm(c_k - experiment(5))
avg_error_5 = avg_error_5 / 1000

avg_error_10 = 0
for i in range(1000):
  avg_error_10 += np.linalg.norm(c_k - experiment(10))
avg_error_10 = avg_error_10 / 1000

avg_error_100 = 0
for i in range(1000):
  avg_error_100 += np.linalg.norm(c_k - experiment(100))
avg_error_100 = avg_error_100 / 1000

print("Average error for n = 5 ", avg_error_5)
print("Average error for n = 10 ", avg_error_10)
print("Average error for n = 100 ", avg_error_100)

<ipython-input-55-4b6ff816ad25>:26: LinAlgWarning: Ill-conditioned matrix (rcond=8.84469e-18): result may not be accurate.
  r_x = solve(augmented_left, augmented_right)
<ipython-input-55-4b6ff816ad25>:26: LinAlgWarning: Ill-conditioned matrix (rcond=6.34585e-17): result may not be accurate.
  r_x = solve(augmented_left, augmented_right)


Average error for n = 5  63201.05064985479
Average error for n = 10  9947.540204176834
Average error for n = 100  1593.0793040909243


In [42]:
 # In order to further investigate the effect of the number of samples, I will also try for n = 1000

avg_error_1000 = 0
for i in range(1000):
  avg_error_1000 += np.linalg.norm(c_k - experiment(1000))
avg_error_1000 = avg_error_1000 / 1000

print("Average error for n = 1000 ", avg_error_1000)

Average error for n = 1000  1029.8845735539326
